"""Cross-department request model and state machine.

Departments run independently. When one needs something from another, it does
not write into a shared task table — it posts a request into the *recipient's*
inbox, and the deliverable travels through the Asset Hub. There is no central
store, only a contract every department implements.

Six constraints are encoded here, each with a reason:

1. **The specification is an asset, not a message body.** Requirements change;
   messages have no version. ``spec_asset_id`` points at a versioned, hashed
   asset instead of pasting prose that immediately goes stale.
2. **Deliverables are assets too**, so lineage ("which shoot produced image 3
   of this article?") is answerable months later.
3. **Acceptance criteria travel with the request.** Being told what "done"
   means only after delivering is the most expensive kind of rework.
4. **Rejection is first class** and must carry a reason. An explicit "I can't
   do this" beats silence — a request that quietly stalls has no exit.
5. **Deadlines escalate.** Expiry is detected by the *recipient's* scheduler,
   so it does not depend on the requester remembering to chase.
6. **Only the requester may close.** A recipient can reach DELIVERED at most;
   declaring your own work accepted is not acceptance.
"""
from __future__ import annotations

import datetime as _dt
import re
from collections.abc import Mapping
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

__all__ = [
    "REASON_REQUIRED",
    "RECIPIENT_ONLY",
    "REQUESTER_ONLY",
    "TERMINAL",
    "TRANSITIONS",
    "CollabRequest",
    "ExpectedDeliverable",
    "Party",
    "Priority",
    "ProtocolError",
    "RequestStatus",
    "new_request_id",
]

_REQUEST_ID_RE = re.compile(r"^REQ-[A-Z0-9]+-\d{8}-\d{4}$")


class ProtocolError(ValueError):
    """A request or transition violates the contract."""


class RequestStatus(str, Enum):
    PENDING = "PENDING"            # delivered into the inbox, not yet triaged
    ACCEPTED = "ACCEPTED"          # recipient took it
    IN_PROGRESS = "IN_PROGRESS"
    BLOCKED = "BLOCKED"            # recipient is stuck, reason required
    DELIVERED = "DELIVERED"        # recipient believes it is done
    RETURNED = "RETURNED"          # requester rejected the delivery
    REJECTED = "REJECTED"          # recipient declined the request outright
    EXPIRED = "EXPIRED"            # deadline passed without delivery
    ESCALATED = "ESCALATED"        # raised to the general manager
    CLOSED = "CLOSED"              # requester accepted — the only success state


class Priority(str, Enum):
    P0 = "P0"
    P1 = "P1"
    P2 = "P2"
    P3 = "P3"


# Legal transitions. Anything absent is rejected, so a bug cannot teleport a
# request into CLOSED.
TRANSITIONS: dict[RequestStatus, frozenset[RequestStatus]] = {
    RequestStatus.PENDING: frozenset(
        {RequestStatus.ACCEPTED, RequestStatus.REJECTED, RequestStatus.EXPIRED}
    ),
    RequestStatus.ACCEPTED: frozenset(
        {RequestStatus.IN_PROGRESS, RequestStatus.BLOCKED, RequestStatus.REJECTED,
         RequestStatus.EXPIRED}
    ),
    RequestStatus.IN_PROGRESS: frozenset(
        {RequestStatus.DELIVERED, RequestStatus.BLOCKED, RequestStatus.EXPIRED}
    ),
    RequestStatus.BLOCKED: frozenset(
        {RequestStatus.IN_PROGRESS, RequestStatus.ESCALATED, RequestStatus.EXPIRED}
    ),
    RequestStatus.DELIVERED: frozenset({RequestStatus.CLOSED, RequestStatus.RETURNED}),
    RequestStatus.RETURNED: frozenset(
        {RequestStatus.IN_PROGRESS, RequestStatus.REJECTED, RequestStatus.EXPIRED}
    ),
    RequestStatus.EXPIRED: frozenset({RequestStatus.ESCALATED, RequestStatus.IN_PROGRESS}),
    RequestStatus.ESCALATED: frozenset(
        {RequestStatus.IN_PROGRESS, RequestStatus.CLOSED, RequestStatus.REJECTED}
    ),
    RequestStatus.REJECTED: frozenset(),
    RequestStatus.CLOSED: frozenset(),
}

TERMINAL: frozenset[RequestStatus] = frozenset({RequestStatus.CLOSED, RequestStatus.REJECTED})

# Constraint 6: acceptance is the requester's call, never the recipient's.
REQUESTER_ONLY: frozenset[RequestStatus] = frozenset(
    {RequestStatus.CLOSED, RequestStatus.RETURNED}
)
RECIPIENT_ONLY: frozenset[RequestStatus] = frozenset(
    {RequestStatus.ACCEPTED, RequestStatus.IN_PROGRESS, RequestStatus.BLOCKED,
     RequestStatus.DELIVERED, RequestStatus.REJECTED}
)

# Constraint 4: a status that means "something went wrong" must say what.
REASON_REQUIRED: frozenset[RequestStatus] = frozenset(
    {RequestStatus.REJECTED, RequestStatus.BLOCKED, RequestStatus.RETURNED,
     RequestStatus.ESCALATED}
)


def new_request_id(dept: str, seq: int, when: _dt.date | None = None) -> str:
    """``REQ-<DEPT>-<YYYYMMDD>-<NNNN>`` — generated by the *requester*.

    Requester-side generation is what makes retries idempotent: a resend
    carries the same id, so the recipient can recognise it as a duplicate
    rather than opening a second ticket.
    """
    day = (when or _dt.datetime.now(_dt.timezone.utc).date()).strftime("%Y%m%d")
    return f"REQ-{dept.upper().replace('-', '')}-{day}-{seq:04d}"


@dataclass(frozen=True)
class Party:
    dept: str
    hm: str = ""
    endpoint: str = ""
    feishu_open_id: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "dept": self.dept, "hm": self.hm,
            "endpoint": self.endpoint, "feishu_open_id": self.feishu_open_id,
        }

    @classmethod
    def from_dict(cls, d: Mapping[str, Any] | None) -> Party:
        d = d or {}
        if not d.get("dept"):
            raise ProtocolError("party.dept 必填")
        return cls(
            dept=str(d["dept"]), hm=str(d.get("hm", "")),
            endpoint=str(d.get("endpoint", "")),
            feishu_open_id=str(d.get("feishu_open_id", "")),
        )


@dataclass(frozen=True)
class ExpectedDeliverable:
    """What "done" looks like — stated up front, not after the fact."""

    asset_class: str = "DOC"
    count: int = 1
    acceptance: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        return {
            "asset_class": self.asset_class,
            "count": self.count,
            "acceptance": list(self.acceptance),
        }

    @classmethod
    def from_dict(cls, d: Mapping[str, Any] | None) -> ExpectedDeliverable:
        d = d or {}
        acceptance = tuple(str(a) for a in (d.get("acceptance") or []))
        if not acceptance:
            raise ProtocolError(
                "expected_deliverable.acceptance 不得为空 —— "
                "验收标准必须在派活时讲清楚,交付后才说是最贵的返工"
            )
        return cls(
            asset_class=str(d.get("asset_class", "DOC")),
            count=int(d.get("count", 1)),
            acceptance=acceptance,
        )


@dataclass
class CollabRequest:
    request_id: str
    sender: Party
    recipient: Party
    capability: str
    title: str
    spec_asset_id: str
    expected: ExpectedDeliverable
    priority: Priority = Priority.P2
    deadline: str = ""                       # ISO-8601
    parent_task: str = ""
    callback: str = ""
    status: RequestStatus = RequestStatus.PENDING
    reason: str = ""
    deliverable_asset_ids: tuple[str, ...] = ()
    created_at: str = ""
    updated_at: str = ""
    history: tuple[dict[str, Any], ...] = field(default_factory=tuple)

    # -- validation --------------------------------------------------------
    def validate(self) -> None:
        if not _REQUEST_ID_RE.match(self.request_id):
            raise ProtocolError(
                f"request_id 格式错误: {self.request_id};应为 REQ-<DEPT>-<YYYYMMDD>-<NNNN>"
            )
        if not self.capability:
            raise ProtocolError("capability 必填 —— 派活前应先查对方 /capabilities")
        if not self.title:
            raise ProtocolError("title 必填")
        # Constraint 1: no prose in the request body.
        if not self.spec_asset_id:
            raise ProtocolError(
                "spec_asset_id 必填 —— 需求正文必须先落成资产。"
                "需求会改,而消息体没有版本;资产有版本、有哈希、有血缘"
            )
        if self.sender.dept == self.recipient.dept:
            raise ProtocolError("不能给自己部门派活,部门内任务用本部门系统")

    def is_overdue(self, now: _dt.datetime | None = None) -> bool:
        if not self.deadline or self.status in TERMINAL:
            return False
        try:
            due = _dt.datetime.fromisoformat(self.deadline)
        except ValueError:
            return False
        now = now or _dt.datetime.now(due.tzinfo or _dt.timezone.utc)
        return now > due

    # -- serialisation -----------------------------------------------------
    def to_dict(self) -> dict[str, Any]:
        return {
            "request_id": self.request_id,
            "from": self.sender.to_dict(),
            "to": {"dept": self.recipient.dept, "capability": self.capability},
            "recipient": self.recipient.to_dict(),
            "title": self.title,
            "spec_asset_id": self.spec_asset_id,
            "expected_deliverable": self.expected.to_dict(),
            "priority": self.priority.value,
            "deadline": self.deadline,
            "parent_task": self.parent_task,
            "callback": self.callback,
            "status": self.status.value,
            "reason": self.reason,
            "deliverable_asset_ids": list(self.deliverable_asset_ids),
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "overdue": self.is_overdue(),
            "history": list(self.history),
        }

    @classmethod
    def from_dict(cls, d: Mapping[str, Any]) -> CollabRequest:
        to = d.get("to") or {}
        recipient_raw = d.get("recipient") or {"dept": to.get("dept", "")}
        req = cls(
            request_id=str(d.get("request_id", "")),
            sender=Party.from_dict(d.get("from")),
            recipient=Party.from_dict(recipient_raw),
            capability=str(to.get("capability", d.get("capability", ""))),
            title=str(d.get("title", "")),
            spec_asset_id=str(d.get("spec_asset_id", "")),
            expected=ExpectedDeliverable.from_dict(d.get("expected_deliverable")),
            priority=Priority(d.get("priority", "P2")),
            deadline=str(d.get("deadline", "")),
            parent_task=str(d.get("parent_task", "")),
            callback=str(d.get("callback", "")),
            status=RequestStatus(d.get("status", "PENDING")),
            reason=str(d.get("reason", "")),
            deliverable_asset_ids=tuple(d.get("deliverable_asset_ids") or []),
            created_at=str(d.get("created_at", "")),
            updated_at=str(d.get("updated_at", "")),
        )
        req.validate()
        return req
